apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.allow-http: "true"
  name: prometheus
  namespace: monitoring
spec:
  rules:
  - host: mykaua.com
    http:
      paths:
      - path: /
        backend:
          serviceName: prometheus
          servicePort: 9090
